# Generated by Django 4.0.6 on 2024-03-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_userblogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userblogmodel',
            name='image',
            field=models.FileField(default='___', upload_to=''),
        ),
    ]
