# Generated by Django 3.2.16 on 2024-03-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_userdatamodel_points_alter_userblogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblogmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='userblogmodel',
            name='isPicturePublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userblogmodel',
            name='numOfPPl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userblogmodel',
            name='numOfTrashPickedUp',
            field=models.IntegerField(default=0),
        ),
    ]
