# Generated by Django 3.2.16 on 2024-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20240309_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogmodel',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
